### PR TITLE
fixed permission error with NamedTemporaryFile on some systems

### PR DESCRIPTION
**Pull request by shahinrostami**

### CODE REVIEW

**Comment by kaibaesler** [comment]
Hi shahinrostami,

the default value of `delete=True` is actually what I intended. I don't want to clutter up my temp directory with dozens of files, and I also don't want to manually remove those tempfiles manually.

That said, I also cannot reproduce the permission problem, but from what I've read on stackoverflow, I assume you're on Windows, right? I only have unix-like systems at hand right now, but I'm willing to take a closer look if you tell me a little more about your setup (Windows- and Python versions you're using, and whether Python is running native or under cygwin/wsl).

Best Regards,
Kai

**Comment by shahinrostami** [comment]
> Hi shahinrostami,
> 
> the default value of `delete=True` is actually what I intended. I don't want to clutter up my temp directory with dozens of files, and I also don't want to manually remove those tempfiles manually.
> 
> That said, I also cannot reproduce the permission problem, but from what I've read on stackoverflow, I assume you're on Windows, right? I only have unix-like systems at hand right now, but I'm willing to take a closer look if you tell me a little more about your setup (Windows- and Python versions you're using, and whether Python is running native or under cygwin/wsl).
> 
> Best Regards,
> Kai

Thank you for the nice extension. It has been a while so I can't remember which machine was causing the issue. It could have been the Windows one. I have been using my own fork since, but it would have been Windows 10, Anaconda 3, Python 3.7 within a conda environment. If you need anything else please let me know.

**Comment by kaibaesler** [comment]
Hi shahinrostami,

thanks for the feedback! I finally got my hands on a Windows machine and was able to reproduce and fix the permission error. Checked on MacOS and Win10, both working fine now.
I'll decline your pull-request now, just to clean things up.

Thanks again for reporting the issue, and for your patience.

Best regards,
Kai

**Comment by shahinrostami** [comment]
> Hi shahinrostami,
> 
> thanks for the feedback! I finally got my hands on a Windows machine and was able to reproduce and fix the permission error. Checked on MacOS and Win10, both working fine now.
> I'll decline your pull-request now, just to clean things up.
> 
> Thanks again for reporting the issue, and for your patience.
> 
> Best regards,
> Kai

Thank you for the excellent work! I still use this extension and so do most of my students. 

Best,

Shahin

**Pull request closed without merging**
